service: jjj-api
frameworkVersion: '>=2.25.2 < 3.0.0'

provider:
  name: aws
  runtime: go1.x
  region: ap-southeast-2
  stage: ${opt:staging, 'dev'}
  useDotenv: true
  lambdaHashingVersion: 20201221
  iam:
    role: arn:aws:iam::292374005836:role/lambda-jaypi
  #  apiGateway:
  #    shouldStartNameWithService: true
  environment:
    JAYPI_TABLE: jaypi

package:
  individually: true
  exclude:
    - ./**

functions:

  # Chune Machine
  chuneMachine:
    handler: source/bin/chuneMachine
    name: chune-machine-${self:provider.stage}
    description: "Listen to what's playing on JJJ"
    memorySize: 128
    timeout: 20
    reservedConcurrency: 1
    package:
      include:
        - ./source/bin/chuneMachine
    environment:
      SPOTIFY_CLIENT_ID: e2d95c4b73d24663b22c220e3c78bb0e
      SPOTIFY_SECRET_ID: 079699d33ca94e37a92f457f71fec846
      REFRESH_QUEUE: https://sqs.ap-southeast-2.amazonaws.com/292374005836/chune-refresh-${self:provider.stage}
      COUNTER_QUEUE: https://sqs.ap-southeast-2.amazonaws.com/292374005836/bean-counter-${self:provider.stage}
    events:
      - sqs:
          arn: arn:aws:sqs:ap-southeast-2:292374005836:chune-refresh-${self:provider.stage}
          batchSize: 1
          enabled: true

  # Bean Counter
  beanCounter:
    handler: source/bin/beanCounter
    name: bean-counter-${self:provider.stage}
    description: "Calculate everyone's points when a song is played"
    memorySize: 128
    timeout: 20
    reservedConcurrency: 1
    package:
      include:
        - ./source/bin/beanCounter
    environment:
      SCORER_QUEUE: https://sqs.ap-southeast-2.amazonaws.com/292374005836/scorer-${self:provider.stage}
    events:
      - sqs:
          arn: arn:aws:sqs:ap-southeast-2:292374005836:bean-counter-${self:provider.stage}
          batchSize: 1
          enabled: true

  # Score Taker
  scoreTaker:
    handler: source/bin/scoreTaker
    name: score-taker-${self:provider.stage}
    description: "Update each voters score"
    memorySize: 128
    timeout: 20
    reservedConcurrency: 100
    package:
      include:
        - ./source/bin/scoreTaker
    events:
      - sqs:
          arn: arn:aws:sqs:ap-southeast-2:292374005836:scorer-${self:provider.stage}
          batchSize: 1
          enabled: true

  # Account
  authorizer:
    handler: source/bin/authorizer
    name: ${self:service}-authorizer-${self:provider.stage}
    description: "Authorizes incoming APIGW requests and verifies the token"
    memorySize: 128
    timeout: 10
    package:
      include:
        - ./source/bin/authorizer

  signup:
    handler: source/bin/signup
    name: account-signup-${self:provider.stage}
    description: "Signup with email and password"
    memorySize: 128
    timeout: 10
    package:
      include:
        - ./source/bin/signup
    events:
      - http:
          path: account/signup
          method: post
          request:
            schema:
              application/json: ${file(schemas/account/signup.json)}

  signin:
    handler: source/bin/signin
    name: account-signin-${self:provider.stage}
    description: "Sign in with email and password"
    memorySize: 128
    timeout: 10
    package:
      include:
        - ./source/bin/signin
    events:
      - http:
          path: account/signin
          method: post
          request:
            schema:
              application/json: ${file(schemas/account/signin.json)}

  authenticate:
    handler: source/bin/oauthAuthenticate
    name: oauth-authenticate-${self:provider.stage}
    description: "Retrieves a login URL for a chosen oauth provider"
    memorySize: 128
    timeout: 10
    package:
      include:
        - ./source/bin/oauthAuthenticate
    events:
      - http:
          path: oauth/{provider}/login
          method: get

  providerRedirect:
    handler: source/bin/oauthProviderRedirect
    name: oauth-redirect-${self:provider.stage}
    description: "Provides a url for oauth providers to redirect to"
    memorySize: 128
    timeout: 10
    package:
      include:
        - ./source/bin/oauthProviderRedirect
    events:
      - http:
          path: oauth/{provider}/redirect
          method: get

  # USERS
  getUser:
    handler: source/bin/getUser
    name: get-user-${self:provider.stage}
    description: "Get a user"
    memorySize: 128
    timeout: 10
    package:
      include:
        - ./source/bin/getUser
    events:
      - http:
          path: user/{userId}
          method: get
          authorizer:
            name: authorizer
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            type: token

  updateUser:
    handler: source/bin/updateUser
    name: update-user-${self:provider.stage}
    description: "Update a user"
    memorySize: 128
    timeout: 10
    package:
      include:
        - ./source/bin/updateUser
    events:
      - http:
          path: user/{userId}
          method: put
          request:
            schema:
              application/json: ${file(schemas/user/update.json)}
  # GROUPS
  createGroup:
    handler: source/bin/createGroup
    name: create-group-${self:provider.stage}
    description: "Creates a group"
    memorySize: 128
    timeout: 10
    package:
      include:
        - ./source/bin/createGroup
    events:
      - http:
          path: group
          method: post
          request:
            schema:
              application/json: ${file(schemas/group/create.json)}

  getGroup:
    handler: source/bin/getGroup
    name: get-group-${self:provider.stage}
    description: "Get a group"
    memorySize: 128
    timeout: 10
    package:
      include:
        - ./source/bin/getGroup
    events:
      - http:
          path: group/{groupId}
          method: get

  updateGroup:
    handler: source/bin/updateGroup
    name: update-group-${self:provider.stage}
    description: "Update a group"
    memorySize: 128
    timeout: 10
    package:
      include:
        - ./source/bin/updateGroup
    events:
      - http:
          path: group/{groupId}
          method: put
          request:
            schema:
              application/json: ${file(schemas/group/update.json)}

  joinGroup:
    handler: source/bin/joinGroup
    name: join-group-${self:provider.stage}
    description: "Join a group"
    memorySize: 128
    timeout: 10
    package:
      include:
        - ./source/bin/joinGroup
    events:
      - http:
          path: group/join
          method: post
          request:
            schema:
              application/json: ${file(schemas/group/join.json)}

  leaveGroup:
    handler: source/bin/leaveGroup
    name: leave-group-${self:provider.stage}
    description: "Leave a group"
    memorySize: 128
    timeout: 10
    package:
      include:
        - ./source/bin/leaveGroup
    events:
      - http:
          path: group/{groupId}/user/{userId}
          method: delete

  getGroupQR:
    handler: source/bin/getGroupQR
    name: get-group-qr-${self:provider.stage}
    description: "Get the QR invite for a group"
    memorySize: 128
    timeout: 10
    package:
      include:
        - ./source/bin/getGroupQR
    events:
      - http:
          path: group/{groupId}/qr
          method: get

  # VOTES
  createVote:
    handler: source/bin/createVote
    name: create-vote-${self:provider.stage}
    description: "Create a vote"
    memorySize: 128
    timeout: 10
    package:
      include:
        - ./source/bin/createVote
    events:
      - http:
          path: user/{userId}/vote
          method: post
          request:
            schema:
              application/json: ${file(schemas/votes/create.json)}

  deleteVote:
    handler: source/bin/deleteVote
    name: delete-vote-${self:provider.stage}
    description: "Delete a vote"
    memorySize: 128
    timeout: 10
    package:
      include:
        - ./source/bin/deleteVote
    events:
      - http:
          path: user/{userId}/vote/{songId}
          method: delete
