name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_DEFAULT_REGION: ap-southeast-2

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GOOS: linux
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Get Dependencies
        working-directory: source/
        run: go mod download

      - name: Build
        working-directory: source/
        run: |
          go build -ldflags="-s -w" -o bin/oauthAuthenticate     rest/oauth/authenticate/main.go
          go build -ldflags="-s -w" -o bin/oauthProviderRedirect rest/oauth/callback/main.go

          go build -ldflags="-s -w" -o bin/createUser     rest/user/createUser/main.go
          go build -ldflags="-s -w" -o bin/getUser        rest/user/getUser/main.go
          go build -ldflags="-s -w" -o bin/updateUser     rest/user/updateUser/main.go

          go build -ldflags="-s -w" -o bin/createGroup    rest/group/createGroup/main.go
          go build -ldflags="-s -w" -o bin/getGroup       rest/group/getGroup/main.go
          go build -ldflags="-s -w" -o bin/updateGroup    rest/group/updateGroup/main.go
          go build -ldflags="-s -w" -o bin/joinGroup      rest/group/joinGroup/main.go
          go build -ldflags="-s -w" -o bin/leaveGroup     rest/group/leaveGroup/main.go
          go build -ldflags="-s -w" -o bin/getGroupQR     rest/group/getGroupQR/main.go

          go build -ldflags="-s -w" -o bin/createVote     rest/votes/createVote/main.go
          go build -ldflags="-s -w" -o bin/deleteVote     rest/votes/deleteVote/main.go

          go build -ldflags="-s -w" -o bin/chuneMachine   lambda/chune-machine/main.go
          go build -ldflags="-s -w" -o bin/beanCounter    lambda/bean-counter/main.go
          go build -ldflags="-s -w" -o bin/scoreTaker     lambda/score-taker/main.go

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: go-binaries
          path: source/bin/*

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: go-binaries
          path: source/bin

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install serverless
        run: npm install -g serverless

      - name: Set file permissions
        working-directory: source/bin
        run: chmod 755 $(find . -type f)

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: serverless deploy --stage dev --SpotifyClientID "${{ secrets.SPOTIFY_CLIENT_ID }}" --SpotifySecretID "${{ secrets.SPOTIFY_SECRET_ID }}"
